// <auto-generated />
namespace Ahl_Vidzy.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class SetMaxValue_NotNull_OverwrireForeignkeyConvention : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SetMaxValue_NotNull_OverwrireForeignkeyConvention));
        
        string IMigrationMetadata.Id
        {
            get { return "202306290429423_SetMaxValue_NotNull_OverwrireForeignkeyConvention"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
